### ISSUE TITLE
Make set/variant an optional attribute

### ISSUE THREAD

**Issue by eelcoj** [Rails-Designer/rails_icons#18]
A current shortcoming of this gem is that a set/variant is required. Some supported libraries don't have multiple variants (maybe just “solid” or “outline”).

Also any custom added library might not have one, giving the user mental overhead to come up with a name. It should also be fairly straight-forward to skip it.

Places it is used:
- https://github.com/Rails-Designer/rails_icons/blob/main/lib/rails_icons/icon.rb#L7
- https://github.com/Rails-Designer/rails_icons/blob/main/lib/rails_icons/icon.rb#L29
- https://github.com/Rails-Designer/rails_icons/blob/main/lib/rails_icons/icon.rb#L50 (could use a small refactor too)
- https://github.com/Rails-Designer/rails_icons/blob/main/lib/rails_icons/icon.rb#L75

**Comment by aamfahim** [comment]
I would like to give this a try 😄

**Comment by jordancalhoun** [comment]
Implementing this may cause issues with the new sync engine (#12) as it relies on the variant key to run.  I can see having a suggestion of solid/outline/etc already in the placeholder for the configuration a simpler solution to this.
